---
version: '2'

volumes:
  mysql_data:
  postgres_data:
    
services:
  # mysql
  mysqld:
    image: sakadonohito/mysql5.6
    volumes:
      - mysql_data:/var/lib/mysql
      - "./mysql/tmp:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "r00tPass"
      MYSQL_DATABASE: "test_db"
      MYSQL_USER: "web"
      MYSQL_PASSWORD: "password"

  # PostgreSQL
  postgres:
    image: postgres:9.5  
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - "./postgres/tmp:/docker-entrypoint-initdb.d"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "Postgres95!"

  # web(php & apache)
  web:
    depends_on:
      - mysqld
      #- postgres
    image: sakadonohito/php5.6.23-apache
    links:
      - mysqld:mysql_host
      - postgres:postgres_host
    ports:
      - "80:80"
    volumes:
      - "./apache/webroot:/var/www/html"
    environment:
      MYSQL_HOST: mysql_host
      POSTGRES_HOST: postgres_host
