---
# data
data: 
  image: sakadonohito/dc:1.0
  #build: "./dataContainer/Dockerfile"

# mysql
mysqld:
  #depends_on: data
  image: sakadonohito/mysql5.6:1.0
  #build: "./mysql/Dockerfile"
  volumes_from:
    - data
  volumes:
    - "~/.vagrant.d/vms/dockerfiles/docker-compose/im-compose/mysql/tmp:/docker-entrypoint-initdb.d"
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: "r00tPass"
    MYSQL_DATABASE: "test_db"
    MYSQL_USER: "web"
    MYSQL_PASSWORD: "password"

# web(php & apache)
web:
  #depends_on: mysqld
  image: sakadonohito/php5.6.23-apache:1.0
  #build: "./apache/Dockerfile"
  links:
    - mysqld:mysql
  ports:
    - "80:80"
  volumes:
    - "~/.vagrant.d/vms/dockerfiles/docker-compose/im-compose/apache/webroot:/var/www/html"
